### ISSUE TITLE
JVM crash while linking bones of a DAC

### ISSUE THREAD

**Issue by stephengold** [stephengold/Maud#8]
To reproduce:
1. Physics -> Add control -> DynamicAnim
2. Physics -> Link tool
3. RMB to select an unlinked bone
4. Link bone
5. Repeat steps 3 and 4 a few times.

Typical console output:
```console
> Task :run
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.jme3.util.ReflectionAllocator (file:/home/sgold/.gradle/caches/modules-2/files-2.1/org.jmonkeyengine/jme3-core/3.5.2-stable/fe2b20c9d088d1d2bcbe08abba9311df2f2dee7a/jme3-core-3.5.2-stable.jar) to method sun.nio.ch.DirectBuffer.cleaner()
WARNING: Please consider reporting this to the maintainers of com.jme3.util.ReflectionAllocator
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f3037aaa911, pid=48471, tid=48489
#
# JRE version: OpenJDK Runtime Environment Temurin-11.0.14.1+1 (11.0.14.1+1) (build 11.0.14.1+1)
# Java VM: OpenJDK 64-Bit Server VM Temurin-11.0.14.1+1 (11.0.14.1+1, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0x5ba911]  AccessInternal::PostRuntimeDispatch<G1BarrierSet::AccessBarrier<1097844ul, G1BarrierSet>, (AccessInternal::BarrierType)2, 1097844ul>::oop_access_barrier(void*)+0x1
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /home/sgold/NetBeansProjects/Maud/core.48471)
#
# An error report file with more information is saved as:
# /home/sgold/NetBeansProjects/Maud/hs_err_pid48471.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
#

> Task :run FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command '/usr/lib/jvm/Temurin/jdk-11.0.14.1+1/bin/java'' finished with non-zero exit value 134

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 39s
```

Typical stack trace from the log;
```log
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f3037aaa911, pid=48471, tid=48489
#
# JRE version: OpenJDK Runtime Environment Temurin-11.0.14.1+1 (11.0.14.1+1) (build 11.0.14.1+1)
# Java VM: OpenJDK 64-Bit Server VM Temurin-11.0.14.1+1 (11.0.14.1+1, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0x5ba911]  AccessInternal::PostRuntimeDispatch<G1BarrierSet::AccessBarrier<1097844ul, G1BarrierSet>, (AccessInternal::BarrierType)2, 1097844ul>::oop_access_barrier(void*)+0x1
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /home/sgold/NetBeansProjects/Maud/core.48471)
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
#

---------------  S U M M A R Y ------------

Command Line: -XX:+UseG1GC -XX:MaxGCPauseMillis=10 -Xms4g -Xmx4g -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant -ea maud.Maud

Host: Intel(R) Core(TM) i5-2320 CPU @ 3.00GHz, 4 cores, 7G, Linux Mint 20.3 Una
Time: Wed Jul 13 12:43:37 2022 PDT elapsed time: 37.940006 seconds (0d 0h 0m 37s)

---------------  T H R E A D  ---------------

Current thread (0x00007f3031138800):  JavaThread "jME3 Main" [_thread_in_vm, id=48489, stack(0x00007f3000179000,0x00007f300027a000)]

Stack: [0x00007f3000179000,0x00007f300027a000],  sp=0x00007f3000276ca0,  free space=1015k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.so+0x5ba911]  AccessInternal::PostRuntimeDispatch<G1BarrierSet::AccessBarrier<1097844ul, G1BarrierSet>, (AccessInternal::BarrierType)2, 1097844ul>::oop_access_barrier(void*)+0x1
j  com.jme3.bullet.collision.PhysicsCollisionObject.findInstance(J)Lcom/jme3/bullet/collision/PhysicsCollisionObject;+0
j  com.jme3.bullet.collision.PhysicsCollisionObject.cloneIgnoreList(Lcom/jme3/util/clone/Cloner;Lcom/jme3/bullet/collision/PhysicsCollisionObject;)V+32
j  com.jme3.bullet.objects.PhysicsRigidBody.cloneFields(Lcom/jme3/util/clone/Cloner;Ljava/lang/Object;)V+18
J 4164 c2 com.jme3.util.clone.Cloner.clone(Ljava/lang/Object;Z)Ljava/lang/Object; (615 bytes) @ 0x00007f3020518228 [0x00007f30205177a0+0x0000000000000a88]
J 4009 c2 com.jme3.util.clone.Cloner.clone(Ljava/lang/Object;)Ljava/lang/Object; (7 bytes) @ 0x00007f30204ef958 [0x00007f30204ef920+0x0000000000000038]
j  maud.model.cgm.CgmPhysics.cloneFields(Lcom/jme3/util/clone/Cloner;Ljava/lang/Object;)V+69
J 4164 c2 com.jme3.util.clone.Cloner.clone(Ljava/lang/Object;Z)Ljava/lang/Object; (615 bytes) @ 0x00007f3020518228 [0x00007f30205177a0+0x0000000000000a88]
J 4009 c2 com.jme3.util.clone.Cloner.clone(Ljava/lang/Object;)Ljava/lang/Object; (7 bytes) @ 0x00007f30204ef958 [0x00007f30204ef920+0x0000000000000038]
j  maud.model.cgm.Cgm.clone()Lmaud/model/cgm/Cgm;+22
j  maud.model.cgm.LoadedCgm.clone()Lmaud/model/cgm/LoadedCgm;+1
j  maud.model.cgm.EditableCgm.clone()Lmaud/model/cgm/EditableCgm;+1
j  maud.model.EditorModel.<init>(Lmaud/model/EditorModel;)V+20
j  maud.model.Checkpoint.<init>(Ljava/util/List;)V+29
j  maud.model.History.addCheckpoint()I+67
j  maud.model.History.autoAdd()V+6
j  maud.model.cgm.EditableCgm.linkBone(Ljava/lang/String;)Z+17
j  maud.model.cgm.SelectedLink.createBoneLink()V+25
j  maud.action.NewAction.process(Ljava/lang/String;)Z+607
j  maud.action.EditorInputMode.onAction(Ljava/lang/String;ZF)V+804
j  jme3utilities.nifty.BasicScreenController.perform(Ljava/lang/String;)V+47
v  ~StubRoutines::call_stub
V  [libjvm.so+0x8d592b]  JavaCalls::call_helper(JavaValue*, methodHandle const&, JavaCallArguments*, Thread*)+0x39b
V  [libjvm.so+0xd13f1d]  invoke(InstanceKlass*, methodHandle const&, Handle, bool, objArrayHandle, BasicType, objArrayHandle, bool, Thread*) [clone .constprop.139]+0x43d
V  [libjvm.so+0xd14f52]  Reflection::invoke_method(oopDesc*, Handle, objArrayHandle, Thread*)+0x102
V  [libjvm.so+0x989668]  JVM_InvokeMethod+0xf8
J 3996  jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Ljava/lang/reflect/Method;Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; java.base@11.0.14.1 (0 bytes) @ 0x00007f30204ed340 [0x00007f30204ed240+0x0000000000000100]
J 2861 c1 jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; java.base@11.0.14.1 (104 bytes) @ 0x00007f30193ab44c [0x00007f30193aa7c0+0x0000000000000c8c]
J 4017 c2 jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; java.base@11.0.14.1 (10 bytes) @ 0x00007f30204f23e8 [0x00007f30204f23a0+0x0000000000000048]
J 1555 c1 java.lang.reflect.Method.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; java.base@11.0.14.1 (65 bytes) @ 0x00007f30190cc064 [0x00007f30190cbd20+0x0000000000000344]
j  de.lessvoid.nifty.NiftyMethodInvoker.callMethod(Ljava/lang/Object;Ljava/lang/reflect/Method;[Ljava/lang/Object;)Ljava/lang/Object;+116
j  de.lessvoid.nifty.NiftyMethodInvoker.performInvoke([Ljava/lang/Object;)V+143
j  de.lessvoid.nifty.Nifty$DelayedMethodInvoke.perform()V+8
j  de.lessvoid.nifty.Nifty.invokeMethods()V+49
J 6816 c1 de.lessvoid.nifty.Nifty$NiftyInputConsumerImpl.processEvent(Lde/lessvoid/nifty/input/NiftyMouseInputEvent;)Z (48 bytes) @ 0x00007f3019bbba4c [0x00007f3019bbb700+0x000000000000034c]
J 6411 c1 de.lessvoid.nifty.Nifty$NiftyInputConsumerImpl.processMouseEvent(IIIIZ)Z (144 bytes) @ 0x00007f3019a9bd74 [0x00007f3019a9bc00+0x0000000000000174]
j  com.jme3.niftygui.InputSystemJme.handleMouseEvent(IZLde/lessvoid/nifty/NiftyInputConsumer;Lcom/jme3/input/event/InputEvent;)V+77
j  com.jme3.niftygui.InputSystemJme.onMouseButtonEventQueued(Lcom/jme3/input/event/MouseButtonEvent;Lde/lessvoid/nifty/NiftyInputConsumer;)V+32
J 6339 c1 com.jme3.niftygui.InputSystemJme.forwardEvents(Lde/lessvoid/nifty/NiftyInputConsumer;)V (134 bytes) @ 0x00007f3019a73494 [0x00007f3019a72b40+0x0000000000000954]
J 6337 c1 de.lessvoid.nifty.Nifty.update()Z (126 bytes) @ 0x00007f3019a7485c [0x00007f3019a746e0+0x000000000000017c]
J 6336 c1 com.jme3.niftygui.InputSystemJme.endInput()V (9 bytes) @ 0x00007f3019a7414c [0x00007f3019a740c0+0x000000000000008c]
J 6480 c1 com.jme3.input.InputManager.processQueue()V (437 bytes) @ 0x00007f3019ad61bc [0x00007f3019ad4720+0x0000000000001a9c]
J 6657 c1 com.jme3.input.InputManager.update(F)V (123 bytes) @ 0x00007f3019b5ac3c [0x00007f3019b5a6e0+0x000000000000055c]
J 6525 c1 com.jme3.app.LegacyApplication.update()V (137 bytes) @ 0x00007f3019af170c [0x00007f3019af0a40+0x0000000000000ccc]
J 6524 c1 com.jme3.app.SimpleApplication.update()V (235 bytes) @ 0x00007f3019aeec74 [0x00007f3019aeeae0+0x0000000000000194]
J 6523 c1 com.jme3.system.lwjgl.LwjglAbstractDisplay.runLoop()V (141 bytes) @ 0x00007f3019aed13c [0x00007f3019aecf40+0x00000000000001fc]
J 6518 c1 com.jme3.system.lwjgl.LwjglDisplay.runLoop()V (149 bytes) @ 0x00007f3019ae80cc [0x00007f3019ae5da0+0x000000000000232c]
j  com.jme3.system.lwjgl.LwjglAbstractDisplay.run()V+136
j  java.lang.Thread.run()V+11 java.base@11.0.14.1
v  ~StubRoutines::call_stub
V  [libjvm.so+0x8d592b]  JavaCalls::call_helper(JavaValue*, methodHandle const&, JavaCallArguments*, Thread*)+0x39b
V  [libjvm.so+0x8d38ed]  JavaCalls::call_virtual(JavaValue*, Handle, Klass*, Symbol*, Symbol*, Thread*)+0x1ed
V  [libjvm.so+0x980d0c]  thread_entry(JavaThread*, Thread*)+0x6c
V  [libjvm.so+0xed489a]  JavaThread::thread_main_inner()+0x1ba
V  [libjvm.so+0xed149f]  Thread::call_run()+0x14f
V  [libjvm.so+0xc714ce]  thread_native_entry(Thread*)+0xee

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  com.jme3.bullet.collision.PhysicsCollisionObject.findInstance(J)Lcom/jme3/bullet/collision/PhysicsCollisionObject;+0
j  com.jme3.bullet.collision.PhysicsCollisionObject.cloneIgnoreList(Lcom/jme3/util/clone/Cloner;Lcom/jme3/bullet/collision/PhysicsCollisionObject;)V+32
j  com.jme3.bullet.objects.PhysicsRigidBody.cloneFields(Lcom/jme3/util/clone/Cloner;Ljava/lang/Object;)V+18
J 4164 c2 com.jme3.util.clone.Cloner.clone(Ljava/lang/Object;Z)Ljava/lang/Object; (615 bytes) @ 0x00007f3020518228 [0x00007f30205177a0+0x0000000000000a88]
J 4009 c2 com.jme3.util.clone.Cloner.clone(Ljava/lang/Object;)Ljava/lang/Object; (7 bytes) @ 0x00007f30204ef958 [0x00007f30204ef920+0x0000000000000038]
j  maud.model.cgm.CgmPhysics.cloneFields(Lcom/jme3/util/clone/Cloner;Ljava/lang/Object;)V+69
J 4164 c2 com.jme3.util.clone.Cloner.clone(Ljava/lang/Object;Z)Ljava/lang/Object; (615 bytes) @ 0x00007f3020518228 [0x00007f30205177a0+0x0000000000000a88]
J 4009 c2 com.jme3.util.clone.Cloner.clone(Ljava/lang/Object;)Ljava/lang/Object; (7 bytes) @ 0x00007f30204ef958 [0x00007f30204ef920+0x0000000000000038]
j  maud.model.cgm.Cgm.clone()Lmaud/model/cgm/Cgm;+22
j  maud.model.cgm.LoadedCgm.clone()Lmaud/model/cgm/LoadedCgm;+1
j  maud.model.cgm.EditableCgm.clone()Lmaud/model/cgm/EditableCgm;+1
j  maud.model.EditorModel.<init>(Lmaud/model/EditorModel;)V+20
j  maud.model.Checkpoint.<init>(Ljava/util/List;)V+29
j  maud.model.History.addCheckpoint()I+67
j  maud.model.History.autoAdd()V+6
j  maud.model.cgm.EditableCgm.linkBone(Ljava/lang/String;)Z+17
j  maud.model.cgm.SelectedLink.createBoneLink()V+25
j  maud.action.NewAction.process(Ljava/lang/String;)Z+607
j  maud.action.EditorInputMode.onAction(Ljava/lang/String;ZF)V+804
j  jme3utilities.nifty.BasicScreenController.perform(Ljava/lang/String;)V+47
v  ~StubRoutines::call_stub
J 3996  jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Ljava/lang/reflect/Method;Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; java.base@11.0.14.1 (0 bytes) @ 0x00007f30204ed2c7 [0x00007f30204ed240+0x0000000000000087]
J 2861 c1 jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; java.base@11.0.14.1 (104 bytes) @ 0x00007f30193ab44c [0x00007f30193aa7c0+0x0000000000000c8c]
J 4017 c2 jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; java.base@11.0.14.1 (10 bytes) @ 0x00007f30204f23e8 [0x00007f30204f23a0+0x0000000000000048]
J 1555 c1 java.lang.reflect.Method.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; java.base@11.0.14.1 (65 bytes) @ 0x00007f30190cc064 [0x00007f30190cbd20+0x0000000000000344]
j  de.lessvoid.nifty.NiftyMethodInvoker.callMethod(Ljava/lang/Object;Ljava/lang/reflect/Method;[Ljava/lang/Object;)Ljava/lang/Object;+116
j  de.lessvoid.nifty.NiftyMethodInvoker.performInvoke([Ljava/lang/Object;)V+143
j  de.lessvoid.nifty.Nifty$DelayedMethodInvoke.perform()V+8
j  de.lessvoid.nifty.Nifty.invokeMethods()V+49
J 6816 c1 de.lessvoid.nifty.Nifty$NiftyInputConsumerImpl.processEvent(Lde/lessvoid/nifty/input/NiftyMouseInputEvent;)Z (48 bytes) @ 0x00007f3019bbba4c [0x00007f3019bbb700+0x000000000000034c]
J 6411 c1 de.lessvoid.nifty.Nifty$NiftyInputConsumerImpl.processMouseEvent(IIIIZ)Z (144 bytes) @ 0x00007f3019a9bd74 [0x00007f3019a9bc00+0x0000000000000174]
j  com.jme3.niftygui.InputSystemJme.handleMouseEvent(IZLde/lessvoid/nifty/NiftyInputConsumer;Lcom/jme3/input/event/InputEvent;)V+77
j  com.jme3.niftygui.InputSystemJme.onMouseButtonEventQueued(Lcom/jme3/input/event/MouseButtonEvent;Lde/lessvoid/nifty/NiftyInputConsumer;)V+32
J 6339 c1 com.jme3.niftygui.InputSystemJme.forwardEvents(Lde/lessvoid/nifty/NiftyInputConsumer;)V (134 bytes) @ 0x00007f3019a73494 [0x00007f3019a72b40+0x0000000000000954]
J 6337 c1 de.lessvoid.nifty.Nifty.update()Z (126 bytes) @ 0x00007f3019a7485c [0x00007f3019a746e0+0x000000000000017c]
J 6336 c1 com.jme3.niftygui.InputSystemJme.endInput()V (9 bytes) @ 0x00007f3019a7414c [0x00007f3019a740c0+0x000000000000008c]
J 6480 c1 com.jme3.input.InputManager.processQueue()V (437 bytes) @ 0x00007f3019ad61bc [0x00007f3019ad4720+0x0000000000001a9c]
J 6657 c1 com.jme3.input.InputManager.update(F)V (123 bytes) @ 0x00007f3019b5ac3c [0x00007f3019b5a6e0+0x000000000000055c]
J 6525 c1 com.jme3.app.LegacyApplication.update()V (137 bytes) @ 0x00007f3019af170c [0x00007f3019af0a40+0x0000000000000ccc]
J 6524 c1 com.jme3.app.SimpleApplication.update()V (235 bytes) @ 0x00007f3019aeec74 [0x00007f3019aeeae0+0x0000000000000194]
J 6523 c1 com.jme3.system.lwjgl.LwjglAbstractDisplay.runLoop()V (141 bytes) @ 0x00007f3019aed13c [0x00007f3019aecf40+0x00000000000001fc]
J 6518 c1 com.jme3.system.lwjgl.LwjglDisplay.runLoop()V (149 bytes) @ 0x00007f3019ae80cc [0x00007f3019ae5da0+0x000000000000232c]
j  com.jme3.system.lwjgl.LwjglAbstractDisplay.run()V+136
j  java.lang.Thread.run()V+11 java.base@11.0.14.1
v  ~StubRoutines::call_stub
```

**Comment by stephengold** [comment]
After removing the `-XX:+UseG1GC` runtime option, the stack trace becomes:
```log
Current thread (0x00007f7275188800):  JavaThread "jME3 Main" [_thread_in_native, id=48997, stack(0x00007f7244e91000,0x00007f7244f92000)]

Stack: [0x00007f7244e91000,0x00007f7244f92000],  sp=0x00007f7244f8ec98,  free space=1015k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libbulletjme.so+0x10b9e1]  Java_com_jme3_bullet_collision_PhysicsCollisionObject_findInstance+0x11
j  com.jme3.bullet.collision.PhysicsCollisionObject.cloneIgnoreList(Lcom/jme3/util/clone/Cloner;Lcom/jme3/bullet/collision/PhysicsCollisionObject;)V+32
j  com.jme3.bullet.objects.PhysicsRigidBody.cloneFields(Lcom/jme3/util/clone/Cloner;Ljava/lang/Object;)V+18
J 4152 c2 com.jme3.util.clone.Cloner.clone(Ljava/lang/Object;Z)Ljava/lang/Object; (615 bytes) @ 0x00007f72640ed56c [0x00007f72640ecb00+0x0000000000000a6c]
J 4008 c2 com.jme3.util.clone.Cloner.clone(Ljava/lang/Object;)Ljava/lang/Object; (7 bytes) @ 0x00007f72640c6c58 [0x00007f72640c6c20+0x0000000000000038]
j  maud.model.cgm.CgmPhysics.cloneFields(Lcom/jme3/util/clone/Cloner;Ljava/lang/Object;)V+69
J 4152 c2 com.jme3.util.clone.Cloner.clone(Ljava/lang/Object;Z)Ljava/lang/Object; (615 bytes) @ 0x00007f72640ed56c [0x00007f72640ecb00+0x0000000000000a6c]
J 4008 c2 com.jme3.util.clone.Cloner.clone(Ljava/lang/Object;)Ljava/lang/Object; (7 bytes) @ 0x00007f72640c6c58 [0x00007f72640c6c20+0x0000000000000038]
j  maud.model.cgm.Cgm.clone()Lmaud/model/cgm/Cgm;+22
j  maud.model.cgm.LoadedCgm.clone()Lmaud/model/cgm/LoadedCgm;+1
j  maud.model.cgm.EditableCgm.clone()Lmaud/model/cgm/EditableCgm;+1
j  maud.model.EditorModel.<init>(Lmaud/model/EditorModel;)V+20
j  maud.model.Checkpoint.<init>(Ljava/util/List;)V+29
j  maud.model.History.addCheckpoint()I+67
j  maud.model.History.autoAdd()V+6
j  maud.model.cgm.EditableCgm.linkBone(Ljava/lang/String;)Z+17
```

**Comment by stephengold** [comment]
I re-tested using the "Minie-5.0.0+debug" library and got the following console output:
```console
> Task :run
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.jme3.util.ReflectionAllocator (file:/home/sgold/.gradle/caches/modules-2/files-2.1/org.jmonkeyengine/jme3-core/3.5.2-stable/fe2b20c9d088d1d2bcbe08abba9311df2f2dee7a/jme3-core-3.5.2-stable.jar) to method sun.nio.ch.DirectBuffer.cleaner()
WARNING: Please consider reporting this to the maintainers of com.jme3.util.ReflectionAllocator
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
warning btCollisionDispatcher::needsCollision: static-static collision!
Jul 13, 2022 1:05:29 PM jme3utilities.nifty.BasicScreenController perform
SEVERE: Caught unexpected throwable:
java.lang.NullPointerException: The PhysicsCollisionObject does not exist.
	at com.jme3.bullet.collision.PhysicsCollisionObject.findInstance(Native Method)
	at com.jme3.bullet.collision.PhysicsCollisionObject.cloneIgnoreList(PhysicsCollisionObject.java:1249)
	at com.jme3.bullet.objects.PhysicsRigidBody.cloneFields(PhysicsRigidBody.java:1161)
	at com.jme3.util.clone.Cloner.clone(Cloner.java:269)
	at com.jme3.util.clone.Cloner.clone(Cloner.java:168)
	at com.jme3.bullet.joints.PhysicsJoint.cloneFields(PhysicsJoint.java:276)
	at com.jme3.bullet.joints.Constraint.cloneFields(Constraint.java:481)
	at com.jme3.bullet.joints.SixDofJoint.cloneFields(SixDofJoint.java:494)
	at com.jme3.util.clone.Cloner.clone(Cloner.java:269)
	at com.jme3.util.clone.Cloner.clone(Cloner.java:168)
	at com.jme3.bullet.animation.PhysicsLink.cloneFields(PhysicsLink.java:677)
	at com.jme3.bullet.animation.BoneLink.cloneFields(BoneLink.java:473)
	at com.jme3.util.clone.Cloner.clone(Cloner.java:269)
	at com.jme3.util.clone.Cloner.clone(Cloner.java:168)
	at com.jme3.util.clone.ListCloneFunction.cloneFields(ListCloneFunction.java:68)
	at com.jme3.util.clone.ListCloneFunction.cloneFields(ListCloneFunction.java:43)
	at com.jme3.util.clone.Cloner.clone(Cloner.java:242)
	at com.jme3.util.clone.Cloner.clone(Cloner.java:168)
	at com.jme3.bullet.animation.DacLinks.cloneFields(DacLinks.java:722)
	at com.jme3.bullet.animation.DynamicAnimControl.cloneFields(DynamicAnimControl.java:897)
	at com.jme3.util.clone.Cloner.clone(Cloner.java:269)
	at com.jme3.util.clone.Cloner.clone(Cloner.java:168)
	at com.jme3.bullet.animation.PhysicsLink.cloneFields(PhysicsLink.java:674)
	at com.jme3.bullet.animation.BoneLink.cloneFields(BoneLink.java:473)
	at com.jme3.util.clone.Cloner.clone(Cloner.java:269)
	at com.jme3.util.clone.Cloner.clone(Cloner.java:168)
	at com.jme3.bullet.collision.PhysicsCollisionObject.cloneFields(PhysicsCollisionObject.java:1398)
	at com.jme3.bullet.objects.PhysicsRigidBody.cloneFields(PhysicsRigidBody.java:1157)
	at com.jme3.util.clone.Cloner.clone(Cloner.java:269)
	at com.jme3.util.clone.Cloner.clone(Cloner.java:168)
	at maud.model.cgm.CgmPhysics.cloneFields(CgmPhysics.java:642)
	at com.jme3.util.clone.Cloner.clone(Cloner.java:269)
	at com.jme3.util.clone.Cloner.clone(Cloner.java:168)
	at maud.model.cgm.Cgm.clone(Cgm.java:1255)
	at maud.model.cgm.LoadedCgm.clone(LoadedCgm.java:346)
	at maud.model.cgm.EditableCgm.clone(EditableCgm.java:1765)
	at maud.model.EditorModel.<init>(EditorModel.java:148)
	at maud.model.Checkpoint.<init>(Checkpoint.java:78)
	at maud.model.History.addCheckpoint(History.java:98)
	at maud.model.History.autoAdd(History.java:132)
	at maud.model.cgm.EditableCgm.linkBone(EditableCgm.java:722)
	at maud.model.cgm.SelectedLink.createBoneLink(SelectedLink.java:194)
	at maud.action.NewAction.process(NewAction.java:115)
	at maud.action.EditorInputMode.onAction(EditorInputMode.java:180)
	at jme3utilities.nifty.BasicScreenController.perform(BasicScreenController.java:267)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at de.lessvoid.nifty.NiftyMethodInvoker.callMethod(NiftyMethodInvoker.java:157)
```

**Comment by stephengold** [comment]
Perhaps there should be a check in `listIgnoredIds()` to make sure all the ids returned by `getObjectWithoutCollision()` are non-zero.

**Comment by stephengold** [comment]
Upgrading Minie to v5.0.1 appears to solve this issue. Perhaps it had to do with ignore lists becoming garbled during a rigid-body rebuild.

I'll keep this issue open until I'm more confident.

**Comment by stephengold** [comment]
I can't reproduce this with top-of-tree, so I believe it's solved.
